export const metadata = {
  title: "Privacy Policy — Langsnap",
};

export default function PrivacyPage() {
  return (
    <article className="prose prose-gray max-w-none">
      <h1>Privacy Policy</h1>
      <p className="text-gray-500 text-sm">Last updated: April 20, 2026</p>

      <p>
        Langsnap ("we", "our", or "us") is operated by Samattana Sawangrak. This Privacy Policy
        explains how we collect, use, and protect your information when you use the Langsnap mobile
        application ("App").
      </p>

      <h2>1. Information We Collect</h2>
      <p>We collect the following information when you use the App:</p>
      <ul>
        <li>
          <strong>Account information</strong> — email address, display name, and username that you
          provide when you create an account.
        </li>
        <li>
          <strong>Profile</strong> — profile avatar you choose within the App.
        </li>
        <li>
          <strong>Learning activity</strong> — words learned, study sessions completed, decks and
          packs finished, and study streaks.
        </li>
        <li>
          <strong>Subscription and purchases</strong> — whether you are on a free or premium plan,
          energy balance, and pack redemption history.
        </li>
        <li>
          <strong>Device token</strong> — a push notification token generated by your device so we
          can send you study reminders. You can disable notifications at any time in your device
          settings.
        </li>
      </ul>

      <h2>2. How We Use Your Information</h2>
      <ul>
        <li>To provide and operate the App and your account.</li>
        <li>To track and display your learning progress.</li>
        <li>To send push notifications (study reminders and updates).</li>
        <li>To manage your subscription and in-app content access.</li>
        <li>To respond to support requests.</li>
      </ul>

      <h2>3. Data Storage</h2>
      <p>
        Your data is stored securely using Supabase (supabase.com), a cloud database provider. Data
        is stored on servers in the region configured for our Supabase project. Supabase complies
        with industry-standard security practices.
      </p>

      <h2>4. Data Sharing</h2>
      <p>
        We do not sell, trade, or share your personal information with third parties, except as
        required by law or to operate the App (e.g., our database provider Supabase).
      </p>

      <h2>5. Data Retention</h2>
      <p>
        We retain your data for as long as your account is active. If you request account deletion,
        we will delete your personal data within 30 days. You can request deletion from within the
        App or by emailing us.
      </p>

      <h2>6. Children&apos;s Privacy</h2>
      <p>
        The App is not directed at children under 13. We do not knowingly collect personal
        information from children under 13. If you believe a child has provided us with personal
        information, please contact us and we will delete it.
      </p>

      <h2>7. Your Rights</h2>
      <p>You have the right to:</p>
      <ul>
        <li>Access the personal data we hold about you.</li>
        <li>Request correction of inaccurate data.</li>
        <li>Request deletion of your account and data.</li>
        <li>Opt out of push notifications via your device settings.</li>
      </ul>

      <h2>8. Changes to This Policy</h2>
      <p>
        We may update this Privacy Policy from time to time. We will notify you of significant
        changes by updating the date at the top of this page. Continued use of the App after changes
        constitutes acceptance of the updated policy.
      </p>

      <h2>9. Contact Us</h2>
      <p>
        If you have any questions or requests regarding this Privacy Policy, please contact us at:{" "}
        <a href="mailto:langsnap@gmail.com">langsnap@gmail.com</a>
      </p>
    </article>
  );
}
